### ISSUE TITLE
Restore Failed with errorcode=-11 iPhone 6,1

### ISSUE THREAD

**Issue by LetsUnlockiPhone** [MatthewPierson/iPhone-5s-OTA-Downgrade-Patches#1]
I tried both own patches and patches from this repo but futurerestore always fail to restore IPSW. Device not able to boot restore mode after pwn dfu mode.

ERROR: Unable to connect to device in restore mode
ERROR: Unable to open device in restore mode
[Error] ERROR: Unable to restore device
Done: restoring failed.
Failed with errorcode=-11

Here is my futurerestore log https://pastebin.com/aU4ZqT2Y
Thanks and help would be appreciated

**Comment by MatthewPierson** [comment]
Is the device booting back to iOS instead of restore mode? I can't see anything in the log that would indicate an issue with my patches, only that the device isn't detected in restore mode. What patches did you use for the iBEC/iBSS that you placed into the IPSW?

**Comment by LetsUnlockiPhone** [comment]
Device reboots to recovery mode (Itunes screen). I tried all possible iBec/iBSS (the one u uploaded + tried my custom made patches as well. And always fails with this error.

**Comment by MatthewPierson** [comment]
Do you have all the dependencies installed for futurerestore? Also, just to be sure, you are using https://github.com/LinusHenze/ipwndfu_public to get into pwndfu and then running "python  	rmsigchks.py" to allow for custom images? What happens if you do a normal futurerestore to some iOS 12 version you have blobs for, does it error the same way? I'm sorry I can't be more helpful, never had this issue on macOS before with futurerestore

**Comment by LetsUnlockiPhone** [comment]
the issue was fixed by patching iBEC without using -v verbose boot arguments
